### ISSUE TITLE
Nested Show error

### ISSUE THREAD

**Issue by Fizzizist** [Fizzizist/Logic2018#3]
Get the following error when attempting to run MP command in nested Show 

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Logic2018.Show.ListSheet(Premise Prem) in /home/fizzizist/Documents/ProjectsDotNet/Logic2018/classes/Show.cs:line 278
   at Logic2018.Show.ShowPremise(Argument argument, Premise toShow, List`1 mainInv) in /home/fizzizist/Documents/ProjectsDotNet/Logic2018/classes/Show.cs:line 75
   at Logic2018.Show.ShowPremise(Argument argument, Premise toShow, List`1 mainInv) in /home/fizzizist/Documents/ProjectsDotNet/Logic2018/classes/Show.cs:line 160
   at Logic2018.Program.Main(String[] args) in /home/fizzizist/Documents/ProjectsDotNet/Logic2018/Program.cs:line 195

**Comment by Fizzizist** [comment]
Only occurs when command is MP 0 PR1 instead of MP PR1 0

Command: MP PR1 0
PR1:(~(P→Q))→Q ∴P→Q
Show: P→Q
0: ~(P→Q)
1: P
2: Q
Command: MP 0 PR1
PR1:(~(P→Q))→Q ∴P→Q
Show: P→Q
0: ~(P→Q)
1: P
2: Q

**Comment by Fizzizist** [comment]
Fixed: had to rewrite Modus Ponens Check and Premise Methods in Rules.cs. Should go back and check other rules as well
