### ISSUE TITLE
error when invoking mc rule on a line that doesn't exist

### ISSUE THREAD

**Issue by Fizzizist** [Fizzizist/Logic2018#8]
Command: ass id
∴((P→Q)→P)→P
Show: P
0: (P→Q)→P
1: ~P
Command: mc 2
Premise input must begin with 'PR' or be an integer.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Logic2018.Show.ShowPremise(Argument argument, Premise toShow, List`1 mainInv) in /home/fizzizist/Documents/projects/Logic2018/classes/Show.cs:line 206
   at Logic2018.Show.ShowPremise(Argument argument, Premise toShow, List`1 mainInv) in /home/fizzizist/Documents/projects/Logic2018/classes/Show.cs:line 221
   at Logic2018.ProblemSet..ctor(Int32 problemSet, String userID) in /home/fizzizist/Documents/projects/Logic2018/classes/ProblemSet.cs:line 90
   at Logic2018.Program.Main(String[] args) in /home/fizzizist/Documents/projects/Logic2018/Program.cs:line 162

**Comment by Fizzizist** [comment]
fixed
